//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCMS {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Menu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Menu() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebCMS.Menu", typeof(Menu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 日期/時間 的當地語系化字串。
        /// </summary>
        public static string _DateTime {
            get {
                return ResourceManager.GetString("_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增帳號 的當地語系化字串。
        /// </summary>
        public static string AddNewUserName {
            get {
                return ResourceManager.GetString("AddNewUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增製圖 的當地語系化字串。
        /// </summary>
        public static string AddTCBook {
            get {
                return ResourceManager.GetString("AddTCBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Alarm 訊息 的當地語系化字串。
        /// </summary>
        public static string AlarmMessage {
            get {
                return ResourceManager.GetString("AlarmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一週警告 的當地語系化字串。
        /// </summary>
        public static string AlarmMonth {
            get {
                return ResourceManager.GetString("AlarmMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 一週警告匯出 的當地語系化字串。
        /// </summary>
        public static string AlarmMonthExport {
            get {
                return ResourceManager.GetString("AlarmMonthExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 即時警告 的當地語系化字串。
        /// </summary>
        public static string AlarmNow {
            get {
                return ResourceManager.GetString("AlarmNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string AlarmType {
            get {
                return ResourceManager.GetString("AlarmType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數值 的當地語系化字串。
        /// </summary>
        public static string AlarmValue {
            get {
                return ResourceManager.GetString("AlarmValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 24小時警告 的當地語系化字串。
        /// </summary>
        public static string AlarmWeek {
            get {
                return ResourceManager.GetString("AlarmWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 24小時警告匯出 的當地語系化字串。
        /// </summary>
        public static string AlarmWeekExport {
            get {
                return ResourceManager.GetString("AlarmWeekExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全部 的當地語系化字串。
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已選取數值 的當地語系化字串。
        /// </summary>
        public static string alreadySelectValueTag {
            get {
                return ResourceManager.GetString("alreadySelectValueTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排程名稱 的當地語系化字串。
        /// </summary>
        public static string ATName {
            get {
                return ResourceManager.GetString("ATName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ATSchedule 的當地語系化字串。
        /// </summary>
        public static string ATSchedule {
            get {
                return ResourceManager.GetString("ATSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 書籤 的當地語系化字串。
        /// </summary>
        public static string BookMark {
            get {
                return ResourceManager.GetString("BookMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大小頭 的當地語系化字串。
        /// </summary>
        public static string bsHead {
            get {
                return ResourceManager.GetString("bsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 建立日期 的當地語系化字串。
        /// </summary>
        public static string buileDate {
            get {
                return ResourceManager.GetString("buileDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解隔離 的當地語系化字串。
        /// </summary>
        public static string cancelPM {
            get {
                return ResourceManager.GetString("cancelPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解隔離中 的當地語系化字串。
        /// </summary>
        public static string cancelPMing {
            get {
                return ResourceManager.GetString("cancelPMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 零件更換紀錄 的當地語系化字串。
        /// </summary>
        public static string ChangeParts {
            get {
                return ResourceManager.GetString("ChangeParts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更您的密碼 的當地語系化字串。
        /// </summary>
        public static string ChangePassward {
            get {
                return ResourceManager.GetString("ChangePassward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 匯出資料 的當地語系化字串。
        /// </summary>
        public static string ChartExport {
            get {
                return ResourceManager.GetString("ChartExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除 的當地語系化字串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 清除選取 的當地語系化字串。
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結案 的當地語系化字串。
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限 的當地語系化字串。
        /// </summary>
        public static string Competence {
            get {
                return ResourceManager.GetString("Competence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 往前推時間 的當地語系化字串。
        /// </summary>
        public static string DataCycle {
            get {
                return ResourceManager.GetString("DataCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料區間 的當地語系化字串。
        /// </summary>
        public static string DataRangeTime {
            get {
                return ResourceManager.GetString("DataRangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料類型 的當地語系化字串。
        /// </summary>
        public static string DataType {
            get {
                return ResourceManager.GetString("DataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 日 的當地語系化字串。
        /// </summary>
        public static string day {
            get {
                return ResourceManager.GetString("day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理狀況 的當地語系化字串。
        /// </summary>
        public static string DealWith {
            get {
                return ResourceManager.GetString("DealWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設值 的當地語系化字串。
        /// </summary>
        public static string DefaultValue {
            get {
                return ResourceManager.GetString("DefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部門 的當地語系化字串。
        /// </summary>
        public static string department_name {
            get {
                return ResourceManager.GetString("department_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下載 的當地語系化字串。
        /// </summary>
        public static string DownLoad {
            get {
                return ResourceManager.GetString("DownLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 繪製 的當地語系化字串。
        /// </summary>
        public static string draw {
            get {
                return ResourceManager.GetString("draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改製圖 的當地語系化字串。
        /// </summary>
        public static string EditTCBook {
            get {
                return ResourceManager.GetString("EditTCBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影響時段及時間 的當地語系化字串。
        /// </summary>
        public static string effectDateTime {
            get {
                return ResourceManager.GetString("effectDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影響生產 的當地語系化字串。
        /// </summary>
        public static string effectOutPut {
            get {
                return ResourceManager.GetString("effectOutPut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇結束時間 的當地語系化字串。
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間請勿選擇超過現在時間 的當地語系化字串。
        /// </summary>
        public static string EndTimeNotOverNowTime {
            get {
                return ResourceManager.GetString("EndTimeNotOverNowTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入 的當地語系化字串。
        /// </summary>
        public static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備FDC資料表 的當地語系化字串。
        /// </summary>
        public static string EqFdcTable {
            get {
                return ResourceManager.GetString("EqFdcTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備上下限設定 的當地語系化字串。
        /// </summary>
        public static string EqLimitSetting {
            get {
                return ResourceManager.GetString("EqLimitSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設備數值資料統計 的當地語系化字串。
        /// </summary>
        public static string eqValueChart {
            get {
                return ResourceManager.GetString("eqValueChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每 的當地語系化字串。
        /// </summary>
        public static string every {
            get {
                return ResourceManager.GetString("every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行週期 的當地語系化字串。
        /// </summary>
        public static string ExecuteCycle {
            get {
                return ResourceManager.GetString("ExecuteCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行時間 的當地語系化字串。
        /// </summary>
        public static string ExecuteTime {
            get {
                return ResourceManager.GetString("ExecuteTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行類型 的當地語系化字串。
        /// </summary>
        public static string ExecuteType {
            get {
                return ResourceManager.GetString("ExecuteType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期五 的當地語系化字串。
        /// </summary>
        public static string friday {
            get {
                return ResourceManager.GetString("friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 氣動閥 的當地語系化字串。
        /// </summary>
        public static string GasValve {
            get {
                return ResourceManager.GetString("GasValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手閥 的當地語系化字串。
        /// </summary>
        public static string HandValve {
            get {
                return ResourceManager.GetString("HandValve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 時 的當地語系化字串。
        /// </summary>
        public static string hour {
            get {
                return ResourceManager.GetString("hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否解隔離 的當地語系化字串。
        /// </summary>
        public static string IsCancelPM {
            get {
                return ResourceManager.GetString("IsCancelPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否刪除 的當地語系化字串。
        /// </summary>
        public static string IsDelete {
            get {
                return ResourceManager.GetString("IsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否有實際PM 的當地語系化字串。
        /// </summary>
        public static string IsHasPM {
            get {
                return ResourceManager.GetString("IsHasPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上限 的當地語系化字串。
        /// </summary>
        public static string IsHiEnable {
            get {
                return ResourceManager.GetString("IsHiEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下限 的當地語系化字串。
        /// </summary>
        public static string IsLoEnable {
            get {
                return ResourceManager.GetString("IsLoEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否隔離 的當地語系化字串。
        /// </summary>
        public static string IsPM {
            get {
                return ResourceManager.GetString("IsPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後修改者 的當地語系化字串。
        /// </summary>
        public static string LastEditUser {
            get {
                return ResourceManager.GetString("LastEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最近更新時間 的當地語系化字串。
        /// </summary>
        public static string LastUpdateTime {
            get {
                return ResourceManager.GetString("LastUpdateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 級別 的當地語系化字串。
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手動上限值 的當地語系化字串。
        /// </summary>
        public static string Limit_Max {
            get {
                return ResourceManager.GetString("Limit_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前上限設定 的當地語系化字串。
        /// </summary>
        public static string Limit_Max_Setting {
            get {
                return ResourceManager.GetString("Limit_Max_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 手動下限值 的當地語系化字串。
        /// </summary>
        public static string Limit_Min {
            get {
                return ResourceManager.GetString("Limit_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 目前下限設定 的當地語系化字串。
        /// </summary>
        public static string Limit_Min_Setting {
            get {
                return ResourceManager.GetString("Limit_Min_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上下限清單 的當地語系化字串。
        /// </summary>
        public static string LimitList {
            get {
                return ResourceManager.GetString("LimitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 柱位 的當地語系化字串。
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入帳號 的當地語系化字串。
        /// </summary>
        public static string Login_name {
            get {
                return ResourceManager.GetString("Login_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號管理 的當地語系化字串。
        /// </summary>
        public static string LoginManage {
            get {
                return ResourceManager.GetString("LoginManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入帳號管理系統 的當地語系化字串。
        /// </summary>
        public static string LogInManageSystem {
            get {
                return ResourceManager.GetString("LogInManageSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入頁面 的當地語系化字串。
        /// </summary>
        public static string LogInPage {
            get {
                return ResourceManager.GetString("LogInPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 L管 的當地語系化字串。
        /// </summary>
        public static string LPipe {
            get {
                return ResourceManager.GetString("LPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自訂 的當地語系化字串。
        /// </summary>
        public static string Manually {
            get {
                return ResourceManager.GetString("Manually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 pm事由 的當地語系化字串。
        /// </summary>
        public static string memo {
            get {
                return ResourceManager.GetString("memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        public static string modify {
            get {
                return ResourceManager.GetString("modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期一 的當地語系化字串。
        /// </summary>
        public static string monday {
            get {
                return ResourceManager.GetString("monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 多數值多設備 的當地語系化字串。
        /// </summary>
        public static string MoreValueTagMoreEq {
            get {
                return ResourceManager.GetString("MoreValueTagMoreEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 水氣分離盒 的當地語系化字串。
        /// </summary>
        public static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼 的當地語系化字串。
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 否 的當地語系化字串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 沒有項目 的當地語系化字串。
        /// </summary>
        public static string nomsg {
            get {
                return ResourceManager.GetString("nomsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選取數值 的當地語系化字串。
        /// </summary>
        public static string noSelectValueTag {
            get {
                return ResourceManager.GetString("noSelectValueTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單一設備多數值 的當地語系化字串。
        /// </summary>
        public static string OneEqMoreValueTag {
            get {
                return ResourceManager.GetString("OneEqMoreValueTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單一數值多設備 的當地語系化字串。
        /// </summary>
        public static string OneValueTagMoreEq {
            get {
                return ResourceManager.GetString("OneValueTagMoreEq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 操作者 的當地語系化字串。
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他 的當地語系化字串。
        /// </summary>
        public static string other {
            get {
                return ResourceManager.GetString("other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 共 的當地語系化字串。
        /// </summary>
        public static string outof {
            get {
                return ResourceManager.GetString("outof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示 第 {from} 項 到 第 {to} 項，總共 {total} 項目 的當地語系化字串。
        /// </summary>
        public static string pagestat {
            get {
                return ResourceManager.GetString("pagestat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 頁次 的當地語系化字串。
        /// </summary>
        public static string pagetext {
            get {
                return ResourceManager.GetString("pagetext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼最少8個字最長20個字 的當地語系化字串。
        /// </summary>
        public static string passwordAtLast {
            get {
                return ResourceManager.GetString("passwordAtLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼輸入錯誤 的當地語系化字串。
        /// </summary>
        public static string PasswordEnterError {
            get {
                return ResourceManager.GetString("PasswordEnterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼須相同 的當地語系化字串。
        /// </summary>
        public static string PasswordMustSame {
            get {
                return ResourceManager.GetString("PasswordMustSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 待處理清單 的當地語系化字串。
        /// </summary>
        public static string PendingList {
            get {
                return ResourceManager.GetString("PendingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不發送 的當地語系化字串。
        /// </summary>
        public static string PhoneCallNotSend {
            get {
                return ResourceManager.GetString("PhoneCallNotSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發送 的當地語系化字串。
        /// </summary>
        public static string PhoneCallSend {
            get {
                return ResourceManager.GetString("PhoneCallSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請檢查輸入 的當地語系化字串。
        /// </summary>
        public static string PlaseCheck {
            get {
                return ResourceManager.GetString("PlaseCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勾選類別 的當地語系化字串。
        /// </summary>
        public static string plaseCheckType {
            get {
                return ResourceManager.GetString("plaseCheckType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫PM理由 的當地語系化字串。
        /// </summary>
        public static string plasePMMemo {
            get {
                return ResourceManager.GetString("plasePMMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇日期 的當地語系化字串。
        /// </summary>
        public static string plaseSelectDate {
            get {
                return ResourceManager.GetString("plaseSelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇部門 的當地語系化字串。
        /// </summary>
        public static string plaseSelectDep {
            get {
                return ResourceManager.GetString("plaseSelectDep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇設備 的當地語系化字串。
        /// </summary>
        public static string plaseSelectEQ {
            get {
                return ResourceManager.GetString("plaseSelectEQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇 的當地語系化字串。
        /// </summary>
        public static string plaseSelectOption {
            get {
                return ResourceManager.GetString("plaseSelectOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇類型 的當地語系化字串。
        /// </summary>
        public static string plaseSelectType {
            get {
                return ResourceManager.GetString("plaseSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請勾選數值名稱 的當地語系化字串。
        /// </summary>
        public static string plaseSelectValueName {
            get {
                return ResourceManager.GetString("plaseSelectValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 機號 的當地語系化字串。
        /// </summary>
        public static string plc_name {
            get {
                return ResourceManager.GetString("plc_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請填寫完整 的當地語系化字串。
        /// </summary>
        public static string PleaseComplete {
            get {
                return ResourceManager.GetString("PleaseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隔離 的當地語系化字串。
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM週期(天) 的當地語系化字串。
        /// </summary>
        public static string pmCycle {
            get {
                return ResourceManager.GetString("pmCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隔離中 的當地語系化字串。
        /// </summary>
        public static string PMing {
            get {
                return ResourceManager.GetString("PMing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 PM中清單 的當地語系化字串。
        /// </summary>
        public static string PMingList {
            get {
                return ResourceManager.GetString("PMingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下次PM時間 的當地語系化字串。
        /// </summary>
        public static string pmNextTime {
            get {
                return ResourceManager.GetString("pmNextTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定pm時間 的當地語系化字串。
        /// </summary>
        public static string pmSet {
            get {
                return ResourceManager.GetString("pmSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 解除pm時間 的當地語系化字串。
        /// </summary>
        public static string pmUnset {
            get {
                return ResourceManager.GetString("pmUnset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋中, 請稍候 ... 的當地語系化字串。
        /// </summary>
        public static string procmsg {
            get {
                return ResourceManager.GetString("procmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢 的當地語系化字串。
        /// </summary>
        public static string Query {
            get {
                return ResourceManager.GetString("Query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢字串 的當地語系化字串。
        /// </summary>
        public static string QueryString {
            get {
                return ResourceManager.GetString("QueryString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理人員 的當地語系化字串。
        /// </summary>
        public static string ReceptionName {
            get {
                return ResourceManager.GetString("ReceptionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重填 的當地語系化字串。
        /// </summary>
        public static string Refill {
            get {
                return ResourceManager.GetString("Refill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 為必填欄位 的當地語系化字串。
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每頁筆數 的當地語系化字串。
        /// </summary>
        public static string rptext {
            get {
                return ResourceManager.GetString("rptext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取樣時間 的當地語系化字串。
        /// </summary>
        public static string SamplingTime {
            get {
                return ResourceManager.GetString("SamplingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期六 的當地語系化字串。
        /// </summary>
        public static string saturday {
            get {
                return ResourceManager.GetString("saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排程 的當地語系化字串。
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全選 的當地語系化字串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 疊圖 的當地語系化字串。
        /// </summary>
        public static string Stack {
            get {
                return ResourceManager.GetString("Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇開始時間 的當地語系化字串。
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期日 的當地語系化字串。
        /// </summary>
        public static string sunday {
            get {
                return ResourceManager.GetString("sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 數值名稱 的當地語系化字串。
        /// </summary>
        public static string TagName {
            get {
                return ResourceManager.GetString("TagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 製圖名稱 的當地語系化字串。
        /// </summary>
        public static string TCName {
            get {
                return ResourceManager.GetString("TCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 臨時拉P 的當地語系化字串。
        /// </summary>
        public static string TemporaryPFlag {
            get {
                return ResourceManager.GetString("TemporaryPFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 三通 的當地語系化字串。
        /// </summary>
        public static string ThreeWay {
            get {
                return ResourceManager.GetString("ThreeWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期四 的當地語系化字串。
        /// </summary>
        public static string thursday {
            get {
                return ResourceManager.GetString("thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱 的當地語系化字串。
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 名稱最長20個字… 的當地語系化字串。
        /// </summary>
        public static string titleLongest {
            get {
                return ResourceManager.GetString("titleLongest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 機台名稱 的當地語系化字串。
        /// </summary>
        public static string ToolId {
            get {
                return ResourceManager.GetString("ToolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入Tool ID後按Enter 的當地語系化字串。
        /// </summary>
        public static string toolidinput {
            get {
                return ResourceManager.GetString("toolidinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 T管 的當地語系化字串。
        /// </summary>
        public static string Tpipe {
            get {
                return ResourceManager.GetString("Tpipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期二 的當地語系化字串。
        /// </summary>
        public static string tuesday {
            get {
                return ResourceManager.GetString("tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 轉彎處 的當地語系化字串。
        /// </summary>
        public static string Turning {
            get {
                return ResourceManager.GetString("Turning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 機型 的當地語系化字串。
        /// </summary>
        public static string typeName {
            get {
                return ResourceManager.GetString("typeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新日期 的當地語系化字串。
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inlet上方彎管 的當地語系化字串。
        /// </summary>
        public static string Upturning {
            get {
                return ResourceManager.GetString("Upturning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入帳號 的當地語系化字串。
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已存在 的當地語系化字串。
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢管理所有帳號 的當地語系化字串。
        /// </summary>
        public static string UserNameManage {
            get {
                return ResourceManager.GetString("UserNameManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號必填 的當地語系化字串。
        /// </summary>
        public static string UserNameMust {
            get {
                return ResourceManager.GetString("UserNameMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 廠商 的當地語系化字串。
        /// </summary>
        public static string Vendor {
            get {
                return ResourceManager.GetString("Vendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 星期三 的當地語系化字串。
        /// </summary>
        public static string wednesday {
            get {
                return ResourceManager.GetString("wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 周 的當地語系化字串。
        /// </summary>
        public static string week {
            get {
                return ResourceManager.GetString("week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 週期 的當地語系化字串。
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是 的當地語系化字串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
