//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMC14B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompareTable
    {
        public int TagIndex { get; set; }
        public string Tagname { get; set; }
        public string Comment { get; set; }
        public string SendBody { get; set; }
        public string VoiceText { get; set; }
        public string SendTo { get; set; }
        public int PriLo { get; set; }
        public int PriHi { get; set; }
        public int ISO { get; set; }
        public bool CallOut { get; set; }
        public string Vendor { get; set; }
        public string MachineType { get; set; }
    }
}
