//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSMC14B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_eq_status
    {
        public short pid { get; set; }
        public string gname { get; set; }
        public string toolid { get; set; }
        public string lid { get; set; }
        public string loc { get; set; }
        public string locSide { get; set; }
        public short typeid { get; set; }
        public Nullable<short> vid { get; set; }
        public string tName { get; set; }
        public string vName { get; set; }
        public string vendor_Intouch { get; set; }
        public byte sid { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> statusdate { get; set; }
    }
}
